# Generated by Django 3.2.16 on 2022-10-19 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='test',
        ),
    ]
